// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account from "./routes/account.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $api_auth_callback from "./routes/api/auth/callback.ts";
import * as $auth_callback from "./routes/auth/callback.tsx";
import * as $contacts from "./routes/contacts.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $elections from "./routes/elections.tsx";
import * as $elections_id_assets from "./routes/elections/[id]/assets.tsx";
import * as $elections_id_ledger from "./routes/elections/[id]/ledger.tsx";
import * as $elections_id_members from "./routes/elections/[id]/members.tsx";
import * as $elections_new from "./routes/elections/new.tsx";
import * as $elections_request from "./routes/elections/request.tsx";
import * as $index from "./routes/index.tsx";
import * as $journals_id_ from "./routes/journals/[id].tsx";
import * as $journals_index from "./routes/journals/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $organizations from "./routes/organizations.tsx";
import * as $organizations_id_assets from "./routes/organizations/[id]/assets.tsx";
import * as $organizations_id_ledger from "./routes/organizations/[id]/ledger.tsx";
import * as $organizations_id_members from "./routes/organizations/[id]/members.tsx";
import * as $organizations_id_settings from "./routes/organizations/[id]/settings.tsx";
import * as $organizations_new from "./routes/organizations/new.tsx";
import * as $pending_review from "./routes/pending-review.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $profile_organization_id_ from "./routes/profile/organization/[id].tsx";
import * as $profile_organization_index from "./routes/profile/organization/index.tsx";
import * as $profile_politician from "./routes/profile/politician.tsx";
import * as $register from "./routes/register.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $sub_accounts from "./routes/sub-accounts.tsx";
import * as $terms from "./routes/terms.tsx";
import * as $verify_organization from "./routes/verify/organization.tsx";
import * as $verify_politician from "./routes/verify/politician.tsx";
import * as $welcome from "./routes/welcome.tsx";
import * as $AddContactModal from "./islands/AddContactModal.tsx";
import * as $ApproveButton from "./islands/ApproveButton.tsx";
import * as $AuthCallback from "./islands/AuthCallback.tsx";
import * as $ContactManager from "./islands/ContactManager.tsx";
import * as $ElectionRequestForm from "./islands/ElectionRequestForm.tsx";
import * as $ElectionSelector from "./islands/ElectionSelector.tsx";
import * as $EmailChangeForm from "./islands/EmailChangeForm.tsx";
import * as $ExportCSVButton from "./islands/ExportCSVButton.tsx";
import * as $ImageCropper from "./islands/ImageCropper.tsx";
import * as $JournalForm from "./islands/JournalForm.tsx";
import * as $JournalFormDrawer from "./islands/JournalFormDrawer.tsx";
import * as $JournalList from "./islands/JournalList.tsx";
import * as $MemberManager from "./islands/MemberManager.tsx";
import * as $NewElectionForm from "./islands/NewElectionForm.tsx";
import * as $NewOrganizationForm from "./islands/NewOrganizationForm.tsx";
import * as $OrganizationManagerVerificationForm from "./islands/OrganizationManagerVerificationForm.tsx";
import * as $OrganizationSelector from "./islands/OrganizationSelector.tsx";
import * as $OrganizationSettingsForm from "./islands/OrganizationSettingsForm.tsx";
import * as $PendingTransfers from "./islands/PendingTransfers.tsx";
import * as $PolicyBanner from "./islands/PolicyBanner.tsx";
import * as $PoliticianProfileForm from "./islands/PoliticianProfileForm.tsx";
import * as $PoliticianVerificationForm from "./islands/PoliticianVerificationForm.tsx";
import * as $ProfileEditor from "./islands/ProfileEditor.tsx";
import * as $ReSyncButton from "./islands/ReSyncButton.tsx";
import * as $ReceiptUploader from "./islands/ReceiptUploader.tsx";
import * as $SubAccountManager from "./islands/SubAccountManager.tsx";
import * as $SyncButton from "./islands/SyncButton.tsx";
import * as $VerificationSection from "./islands/VerificationSection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account.tsx": $account,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/api/auth/callback.ts": $api_auth_callback,
    "./routes/auth/callback.tsx": $auth_callback,
    "./routes/contacts.tsx": $contacts,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/elections.tsx": $elections,
    "./routes/elections/[id]/assets.tsx": $elections_id_assets,
    "./routes/elections/[id]/ledger.tsx": $elections_id_ledger,
    "./routes/elections/[id]/members.tsx": $elections_id_members,
    "./routes/elections/new.tsx": $elections_new,
    "./routes/elections/request.tsx": $elections_request,
    "./routes/index.tsx": $index,
    "./routes/journals/[id].tsx": $journals_id_,
    "./routes/journals/index.tsx": $journals_index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/organizations.tsx": $organizations,
    "./routes/organizations/[id]/assets.tsx": $organizations_id_assets,
    "./routes/organizations/[id]/ledger.tsx": $organizations_id_ledger,
    "./routes/organizations/[id]/members.tsx": $organizations_id_members,
    "./routes/organizations/[id]/settings.tsx": $organizations_id_settings,
    "./routes/organizations/new.tsx": $organizations_new,
    "./routes/pending-review.tsx": $pending_review,
    "./routes/privacy.tsx": $privacy,
    "./routes/profile/organization/[id].tsx": $profile_organization_id_,
    "./routes/profile/organization/index.tsx": $profile_organization_index,
    "./routes/profile/politician.tsx": $profile_politician,
    "./routes/register.tsx": $register,
    "./routes/settings.tsx": $settings,
    "./routes/sub-accounts.tsx": $sub_accounts,
    "./routes/terms.tsx": $terms,
    "./routes/verify/organization.tsx": $verify_organization,
    "./routes/verify/politician.tsx": $verify_politician,
    "./routes/welcome.tsx": $welcome,
  },
  islands: {
    "./islands/AddContactModal.tsx": $AddContactModal,
    "./islands/ApproveButton.tsx": $ApproveButton,
    "./islands/AuthCallback.tsx": $AuthCallback,
    "./islands/ContactManager.tsx": $ContactManager,
    "./islands/ElectionRequestForm.tsx": $ElectionRequestForm,
    "./islands/ElectionSelector.tsx": $ElectionSelector,
    "./islands/EmailChangeForm.tsx": $EmailChangeForm,
    "./islands/ExportCSVButton.tsx": $ExportCSVButton,
    "./islands/ImageCropper.tsx": $ImageCropper,
    "./islands/JournalForm.tsx": $JournalForm,
    "./islands/JournalFormDrawer.tsx": $JournalFormDrawer,
    "./islands/JournalList.tsx": $JournalList,
    "./islands/MemberManager.tsx": $MemberManager,
    "./islands/NewElectionForm.tsx": $NewElectionForm,
    "./islands/NewOrganizationForm.tsx": $NewOrganizationForm,
    "./islands/OrganizationManagerVerificationForm.tsx":
      $OrganizationManagerVerificationForm,
    "./islands/OrganizationSelector.tsx": $OrganizationSelector,
    "./islands/OrganizationSettingsForm.tsx": $OrganizationSettingsForm,
    "./islands/PendingTransfers.tsx": $PendingTransfers,
    "./islands/PolicyBanner.tsx": $PolicyBanner,
    "./islands/PoliticianProfileForm.tsx": $PoliticianProfileForm,
    "./islands/PoliticianVerificationForm.tsx": $PoliticianVerificationForm,
    "./islands/ProfileEditor.tsx": $ProfileEditor,
    "./islands/ReSyncButton.tsx": $ReSyncButton,
    "./islands/ReceiptUploader.tsx": $ReceiptUploader,
    "./islands/SubAccountManager.tsx": $SubAccountManager,
    "./islands/SyncButton.tsx": $SyncButton,
    "./islands/VerificationSection.tsx": $VerificationSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
